-- ============================================================================
-- Loads sql/transactions/*.csv into the fact tables
-- Run AFTER schema.sql and load_seed_data.sql (dimensions must exist first)
-- Usage: psql -d mantrac_dw -f load_transactions.sql
-- ============================================================================

\copy fact_equipment_sales (sale_id, equipment_id, customer_id, sale_date, sale_price, cost_basis, salesperson) FROM 'fact_equipment_sales.csv' WITH (FORMAT csv, HEADER true);

\copy fact_rental_contracts (rental_id, equipment_id, customer_id, start_date, end_date, rate_type, rate, total_billed, actual_usage_hours) FROM 'fact_rental_contracts.csv' WITH (FORMAT csv, HEADER true, FORCE_NULL(end_date));

\copy fact_maintenance_events (work_order_id, equipment_id, customer_id, technician_id, maintenance_type, priority, source_signal_id, scheduled_date, actual_start, actual_completion, downtime_hours, sla_target_hours, labor_hours, total_cost, warranty_flag, status, root_cause, follow_up_required) FROM 'fact_maintenance_events.csv' WITH (FORMAT csv, HEADER true, FORCE_NULL(source_signal_id, root_cause));

\copy fact_maintenance_parts_used (work_order_id, part_id, qty_used) FROM 'fact_maintenance_parts_used.csv' WITH (FORMAT csv, HEADER true);

\copy fact_tax_filings (filing_id, customer_id, period_start, period_end, vat_amount, nhil_amount, getfund_amount, withholding_tax_amount, filing_status) FROM 'fact_tax_filings.csv' WITH (FORMAT csv, HEADER true);

\copy fact_telemetry_daily (equipment_id, date_id, engine_hours, utilization_hours, fault_count_info, fault_count_warning, fault_count_critical, avg_sensor_reading, max_sensor_reading) FROM 'fact_telemetry_daily.csv' WITH (FORMAT csv, HEADER true);

-- Generated by spark/jobs/predictive_maintenance_scoring.py + merge_signals_output.py
-- (must be loaded AFTER fact_telemetry_daily since the scoring job depends on it)
\copy ml_maintenance_signals (signal_id, equipment_id, scoring_date, predicted_component_id, failure_probability, model_version, recommended_action_window_days, contributing_fault_codes, signal_status, dismiss_reason, created_at) FROM 'ml_maintenance_signals.csv' WITH (FORMAT csv, HEADER true, FORCE_NULL(contributing_fault_codes, dismiss_reason));

SELECT setval(pg_get_serial_sequence('ml_maintenance_signals', 'signal_id'), (SELECT MAX(signal_id) FROM ml_maintenance_signals));

-- Generated by pipeline/resolve_parts_demand.py (run AFTER apply_triage_rules.py)
\copy parts_demand_forecast (forecast_id, signal_id, equipment_id, part_id, expected_qty, is_primary, needed_by_date, demand_source) FROM 'parts_demand_forecast.csv' WITH (FORMAT csv, HEADER true);
\copy parts_mapping_gaps (gap_id, signal_id, component_id, model_id, resolved) FROM 'parts_mapping_gaps.csv' WITH (FORMAT csv, HEADER true);

\copy fact_inventory (part_id, branch, snapshot_date, qty_on_hand, unit_cost, reorder_point, days_of_supply) FROM 'fact_inventory.csv' WITH (FORMAT csv, HEADER true);

-- Reset sequence counters
SELECT setval(pg_get_serial_sequence('fact_equipment_sales', 'sale_id'), (SELECT MAX(sale_id) FROM fact_equipment_sales));
SELECT setval(pg_get_serial_sequence('fact_rental_contracts', 'rental_id'), (SELECT MAX(rental_id) FROM fact_rental_contracts));
SELECT setval(pg_get_serial_sequence('fact_maintenance_events', 'work_order_id'), (SELECT MAX(work_order_id) FROM fact_maintenance_events));
SELECT setval(pg_get_serial_sequence('fact_tax_filings', 'filing_id'), (SELECT MAX(filing_id) FROM fact_tax_filings));
